FROM ubuntu:22.04

# Cập nhật hệ thống và cài các gói cần thiết
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    software-properties-common

# Thêm kho Kubernetes
RUN curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

# Cài đặt kubeadm, kubelet, kubectl
RUN apt-get update && apt-get install -y \
    kubelet \
    kubeadm \
    kubectl && \
    apt-mark hold kubelet kubeadm kubectl

# Tắt swap (Kubernetes yêu cầu)
RUN swapoff -a

# Mặc định chạy bash
CMD ["/bin/bash"]
